CREATE TABLE gerentes(
    id_gerente INT AUTO_INCREMENT PRIMARY KEY,
    nome_gerente STRING NOT NULL VARCHAR(100) UNIQUE,
    login STRING NOT NULL VARCHAR(20) UNIQUE,
    password STRING NOT NULL VARCHAR(100),
    email STRING NOT NULL VARCHAR(100),
    telefone STRING NOT NULL VARCHAR(20)
    
);