

# Configuracoes do banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_gestaobiblioteca
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.flyway.baselineOnMigrate=true
spring.datasource.initialization-mode=never
spring.jpa.show_sql = true

# Configurcoes do servidor
server.port=8080

# Configuracoes do Token JWT
api.security.token.secret=${JWT_SECRET:my-secret-key}
